services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - TZ=America/Moncton

    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - /mnt/graid/Media/Movies:/data/movies:ro
      - "/mnt/graid/Media/TV Shows:/data/tv:ro"

    restart: unless-stopped
