services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    ports:
      - "3002:3000"

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "192.168.x.x:3002,100.x.x.x:3002"

    volumes:
      - homepage_config:/app/config

volumes:
  homepage_config:
